resources:
- name: ci
  type: git
  source:
    uri: https://github.com/concourse/examples.git

jobs:
- name: the-best-job
  plan:
  - get: ci
  - task: today
    file: ci/tasks/print-date.yml

# fly -t tutorial set-pipeline -p sample-pipeline -c pipeline.yml