var_sources:
- name: dumb
  type: dummy
  config:
    vars:
      simple: hello!
      user:
        username: big
        password: sekrit

jobs:
- name: print-creds
  plan:
  - task: print
    config:
      platform: linux

      image_resource:
        type: registry-image
        source: {repository: ubuntu}

      run:
        path: bash
        args:
        - -c
        - |
          echo simple: ((dumb:simple))
          echo username: ((dumb:user.username))
          echo password: ((dumb:user.password))